### ISSUE TITLE
Tuple does not seem to work.

### ISSUE THREAD

**Issue by migeed-z** [mvitousek/reticulated#10]
The program below does not typecheck.
class A:
    def m(self)->Tuple(A):
        return (self,self)
print(A().m())

Here's the error message:
====STATIC TYPE ERROR=====
/Users/zeinamigeed/Documents/reticulated/reticulated-master/docs/tutorial6.py:6:8: A return value of type Tuple(Object(A, {'m': Function([], Tuple(TypeVar(A)))})) was expected but a value of type Tuple(Dyn,Dyn) was returned instead. (code RETURN_ERROR)

When I replace Tuple with List, the program typechecks and runs fine.

**Comment by mvitousek** [comment]
The Tuple type doesn't work quite like the List type does. The `Tuple` type constructor's arguments are the types of each individual element of the tuple. The value `(self, self)` has the type `Tuple(A, A)`, because it's a tuple with two elements of type `A` -- the program runs successfully if you change the type annotation to that. The type `Tuple(A)` corresponds to 1-element tuples where the only element is an `A`. 

You can also have heterogeneous tuple types like `Tuple(A, int)` which could be inhabited by `(self, 42)`.

Let me know if I can clarify more.
